name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --with dev

      - name: Ruff
        run: poetry run ruff check vidgrab/

      - name: Pylint
        run: poetry run pylint vidgrab/

      - name: Mypy
        run: poetry run mypy vidgrab/ --ignore-missing-imports --strict

      - name: Markdownlint
        run: npx --yes markdownlint-cli2 "**/*.md" "#node_modules"
